# Generated by Django 3.2 on 2022-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='screen_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
