# Generated by Django 3.2 on 2022-02-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_account_twitter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='access_token_secret',
            field=models.TextField(default='ds', editable=False),
        ),
    ]
