# Generated by Django 3.2 on 2022-02-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_account_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_token_secret',
            field=models.TextField(),
        ),
    ]
