# Generated by Django 3.2 on 2022-02-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_accesstoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
